# Generated by Django 3.1.5 on 2021-01-20 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='nane',
            new_name='name',
        ),
    ]
