# Generated by Django 3.1.5 on 2021-01-21 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_assig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assig',
            name='member_id',
        ),
        migrations.AddField(
            model_name='assig',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.member'),
        ),
    ]
