# Generated by Django 3.1.5 on 2021-01-22 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210121_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assig',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigs', to='core.member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='adress',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='members_profille'),
        ),
        migrations.AlterField(
            model_name='member',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
